#!/bin/sh

source /etc/env/aliasrc

export HISTSIZE=3000
export HISTTIMEFORMAT="%F %T "
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
unset HISTCONTROL

export PATH=$PATH:$HOME/bin
export PATH=$PATH:/usr/java/jdk1.8.0_131/bin
export PATH=$PATH:/opt/node-v12.16.1-linux-x64/bin
export PATH=$PATH:/data/sparrow/bin

